resources/docs/creating-chirps.md, resources/docs/installation.md, resources/docs/showing-chirps.md
Now that the user has a choice of `artisan serve` or Sail, this PR updates any references to the Sail-specific URL to either mention both, or remove it where possible.
This PR also:
* Makes the `artisan serve` URL a link to allow easy navigation to it.
* Copies the screenshot from the Docker section to the Quick Start section.
* Adds some text after we first load the page with Vue/React to mention the automatic reloading via Vite.
=> Update development server links

resources/docs/installation.md
Commit [#1acdc5b](https://github.com/laravel/bootcamp.laravel.com/commit/1acdc5b051c8941e647f9c6b7de2c0b67a13efda) replaces all the instances of `./vendor/bin/sail artisan` with `php artisan`, so a mention of `sail artisan` might be useful for those sticking with sail.
=> Add hint about using Artisan via Sail

resources/views/docs.blade.php
This PR fixes a bug where the expandable headings wouldn't expand on mobile.
The problem was due to the `<script>` tag that activates them coming *before* the mobile nav in the DOM, so I've moved it to the bottom with the rest of the scripts.
While doing this, I noticed a bunch of dead navigation code. The template for this site was taken from the Laravel docs website which also has this issue. There is a separate navigation menu that is set up to display when pressing a button, however, the nav and its button never appear because they're hidden at the `lg` breakpoint, while the container they're in only shows at the `lg` breakpoint.
=> Fix expandable headings on mobile

resources/views/docs.blade.php
Floating cubes at the bottom of navigation making navigation links unreachable.
As shown in above picture, Deploying and Conclusion links are not reachable for those floating cubes.
I pushed floating blocks below to the navigation links and still stick to bottom as previously was.
=> Fix cubes making navigation link unreachable

resources/docs/inertia/editing-chirps.md
Arrow function missing curly braces causing compile errors when working through react examples.
=> Fix arrow function syntax in edit react example

config/torchlight.php
Enabled visual difference indicators in Torchlight config file to increase visual accessibility (re: [this Discord post](https://discord.com/channels/297040613688475649/1060586040353620139))
=> Enabled Torchlight visual difference indicators

resources/docs/inertia/creating-chirps.md
While following [the creating chirps example on Laravel Bootcamp](https://bootcamp.laravel.com/inertia/creating-chirps#inertia), the error below is thrown after generating and navigating to the **Chirps/Index** page component. This issue is specific to the React example provided in the Laravel Bootcamp docs.
The issue occurs because, whereas the React example on Laravel Bootcamp passes an `auth` prop to the `AuthenticatedLayout` component, [the underlying implementation for `AuthenticatedLayout` in Laravel Breeze](https://github.com/laravel/breeze/blob/1.x/stubs/inertia-react/resources/js/Layouts/AuthenticatedLayout.jsx#L8) has no `auth` prop, but requires a `user` prop instead.
This is the reason why the `name` property of the `user` object is inaccessible because `user` is `undefined`. …
=> Fix creating-chirps.md

resources/docs/inertia/deleting-chirps.md, resources/docs/inertia/editing-chirps.md
It is correct to use className instead of class in React code.
Class was used in the following two places.
```console
> find . -type f -name "*.md" -print0 | xargs -0 -I{} awk '/^```javascript tab=React/,/^```$/{print FILENAME ":" FNR ":" $0}' {} | grep 'class='
./resources/docs/inertia/deleting-chirps.md:372:                        <InputError message={errors.message} class="mt-2" />
./resources/docs/inertia/editing-chirps.md:189:                        <InputError message={errors.message} class="mt-2" />
```
=> Fix class to className in React code

resources/docs/introduction.md
On the home page, I noticed the two stack selection links get a little bit lost on the page with the other links:
This PR changes those into buttons (taken from the laravel.com home page):
They have the same hover effect as the home page too:
=> Highlight stack selections on home page

resources/css/_code.css, resources/css/app.css
This PR is a continuation of #14 keeping the code element inline and also applying the change reviewed by @jessarcher to make the CSS selectors more explicit.
I've tried all pages to look for more overflow issues and I found at least two pages that the tables were also overflowing, I applied similar tailwind properties to solve it as well.
```css
li code,
p code {
@apply inline-flex max-w-full overflow-scroll
}
table {
@apply block max-w-full overflow-scroll
}
```
`inline-flex` or `display: inline-flex` is similar to `display: inline-block` but using the `flex` property. Unfortunately I didn't understood quite well so here is the [link](https://stackoverflow.com/questions/27418104/whats-the-difference-between-displayinline-flex-and-displayflex) for more info about it. I had to use it …
=> Fix pages overflow

resources/docs/notifications-and-events.md
The [Notifications & Events](https://bootcamp.laravel.com/inertia/notifications-and-events) page has the user go through quite a few steps before getting to the "Testing it Out" section. Once they get there, it only tells them what to do if they use Sail, leaving others a little in the dark.
This PR tweaks the wording to guide non-Sail users towards Mailpit (or any other email testing tool like HELO) or using the `log` mailer.
Thanks to @simonswiss for the feedback!
=> Improve mail testing section for non-Sail users

resources/docs/blade/creating-chirps.md, resources/docs/inertia/creating-chirps.md
When to explain how to update the migration file in both (inertia and blade tutorials), the directory name is wrong. The correct name to migration files is `migrations`.
Follow the image on both cases:
*Blade tutorial:*
*Inertia tutorial:*
=> fix: changed migration directory name to migrations

resources/docs/livewire/deleting-chirps.md, resources/docs/livewire/editing-chirps.md, resources/docs/livewire/showing-chirps.md
Editing chirps breaks after adding a chirp.  Add wire:key to the Chirp list component as a fix.
=> Fix Livewire chirp display 

resources/docs/blade/creating-chirps.md, resources/docs/livewire/creating-chirps.md
This PR is repair the docs of how to get all the chirps via artisan Tinker in sections Build Chirper with Blade and Build Chirper with Livewire. Previously, if I run command `Chirp::all();` then Tinker will give error message **Class "Chirp" not found.** In order to make it works, I replace with command `App\Models\Chirp::all();`.
=> Fix display chirps in artisan tinker

resources/docs/livewire/deleting-chirps.md, resources/docs/livewire/editing-chirps.md
This PR are fix editing chirper and add a confirmation pop up when delete a chirper using `wire:confirm`.
Livewire reset the order of chirps when I'm editing a chirp. In this case, I have a lot of chirps. Here's the video.
**Before**
The video below is the result of editing chirp has been fixed and add confirmation when delete a chirp.
**After**
I'm also create a chirper repository in Livewire (class & functional) and it contains a commit of fix editing a chirper.
Livewire Class: https://github.com/kresnasatya/chirper/commit/84d31339e3b1369cd17f48dd45bc35ab2939f3da, https://github.com/kresnasatya/chirper/tree/livewire
Livewire Functional: https://github.com/kresnasatya/chirper/commit/cc1977c266df8ff0b9432dec7fdfafda148c696a, https://github.com/kresnasatya/chirper/tree/livewire-functional
=> Fix Editing Chirper and Add Confirm Delete Chirper in Livewire

resources/docs/inertia/creating-chirps.md
Fixes a continuation error in the inertia path of the bootcamp. The diff initially shows the index method returning a `response` but the diff on the next step shows the index method returning a raw string.
=> Makes diff removed line match previous example

package-lock.json, resources/docs/inertia/creating-chirps.md
I think the user property does not go inside the AuthenticatedLayour in the markdown file creating chirps generates an error and makes it impossible to follow the documentation and then later in the docs itself they change the style.
=> A property fails due to docs Innertia/laravel

package-lock.json, resources/docs/inertia/creating-chirps.md
The PR reverts laravel/bootcamp.laravel.com#60 which incorrectly changed the props passed to the `AuthenticatedLayout` component to not work with current versions of Breeze.
=> Revert "A property fails due to docs Innertia/laravel"

resources/docs/blade/installation.md, resources/docs/inertia/installation.md, resources/docs/livewire/installation.md
If an old version of PHP is installed, then Composer may install old versions of packages which may not work with the instructions in the Bootcamp.
Composer warns about not using the latest version, but it's easy to miss with the output that follows:
Rather than hardcode specific versions in the Bootcamp, which would need to be continually updated. This PR adds a note to encourage users to check that they have a currently supported version of PHP, linking to PHP's supported version documentation.
=> Add note about required PHP version

resources/docs/inertia/editing-chirps.md
There's a trait missing in `ChirpController` in [this part](https://laravel.com/docs/11.x/releases#base-controller-class) of the editing chapter. I'm guessing it got lost since the bump to laravel 11 a few days ago. These traits are not part of the base controller anymore: https://laravel.com/docs/11.x/releases#base-controller-class
I'm not that familiar with PHP, so I probably missed something here. Consider this a bug report rather than a complete fix in that case 😊
=> add a missing trait to the inertia guide

resources/docs/blade/deleting-chirps.md, resources/docs/blade/editing-chirps.md
The Gate facade appears to be needed due to the new default Controller configuration. I.e. ChirpController->authorize() does not exist by default. This is my first day trying Laravel so I could be way off here.
=> Add Gate facade to Blade tutorial

resources/docs/notifications-and-events.md
Since there's no need to manually register the listener in 11, this part isn't needed. I confirmed that [the auto discovery](https://laravel.com/docs/11.x/events#event-discovery) works here as expected.
I'm sure there's tons of other details that needs to be updated for 11, I'm just trying to fix the once I run into.
=> remove the step to manually register the event listener

resources/docs/blade/editing-chirps.md, resources/docs/inertia/editing-chirps.md
When I tried to learn the bootcamp flow yesterday, there was a slight shortcoming in the editing section, the chirps use Gate was not highlighted even though it was used. Maybe this can help other people who want to follow that the Gate must be imported. 😁
=> Add highlight use Facade\Gate

resources/docs/notifications-and-events.md
The default queue driver in Laravel 11 has changed to `database` instead of `sync`. So the Notifications & Events section wouldn't work if followed, since the queued notification is never handled. One would need to start the worker or change the `QUEUE_CONNECTION` to `sync`
=> Update notification section to reflect Laravel 11

resources/docs/inertia/creating-chirps.md, resources/docs/inertia/showing-chirps.md
This PR removes invalid props from the `AuthenticatedLayout` layout component within the `resources/docs/inertia` React docs.
`creating-chirps.md` shows the `AuthenticatedLayout` layout component having a `user` prop.
`showing-chirps.md` shows the `AuthenticatedLayout`  layout component having an `auth` prop.
The current React prop type on the `AuthenticatedLayout` layout component is `PropsWithChildren<{ header?: ReactNode }>`.
- [Breeze Inertia JavaScript Component](https://github.com/laravel/breeze/blob/2.x/stubs/inertia-react/resources/js/Layouts/AuthenticatedLayout.jsx)
- [Breeze Inertia Typescript Component](https://github.com/laravel/breeze/blob/2.x/stubs/inertia-react-ts/resources/js/Layouts/AuthenticatedLayout.tsx)
If the user chooses to modify the tutorial to use typescript …
=> Remove invalid `AuthenticatedLayout` props from inertia react docs
